seed: 42

model:
  hidden_dim: 128
  num_layers: 4

physics:
  nu: 0.01
  inlet_velocity: 1.0

optimizer:
  lr: 1e-3

scheduler:
  decay_rate: 0.999

training:
  max_steps: 1500000
  log_every: 1000

batch_size:
  Inlet: 500
  Outlet: 500
  NoSlip: 10000
  InteriorLR: 2000
  InteriorHR: 2000
  IntegralContinuity: 10000
  MonitorPlane: 1024

loss:
  Inlet: 1.0
  Outlet: 1.0
  NoSlip: 1.0
  InteriorLR: 1.0
